apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  type: csi
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gp3